# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

# event listener for json respons
     api_exception_subscriber:
            class: AppBundle\EventListener\ApiExceptionJson
            arguments: []
            tags:
                - { name: kernel.event_subscriber }

     app.file_uploader:
             class: AppBundle\Service\FileUploader
             arguments: ['%upload_path%'] #argument from config/parameter


